# Generated by Django 5.2.3 on 2025-06-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='area',
            field=models.CharField(choices=[('Ventas', 'Ventas'), ('Operaciones', 'Operaciones'), ('TI Interna', 'TI Interna'), ('Recursos Humanos', 'Recursos Humanos'), ('Finanzas', 'Finanzas')], max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='type',
            field=models.CharField(choices=[('Hardware', 'Hardware'), ('Software', 'Software'), ('Red', 'Red')], max_length=50),
        ),
    ]
